### ISSUE TITLE
Inconsistencies following upgrade

### ISSUE THREAD

**Issue by hwaterer** [mwt/zoom-apt-repo#12]
Hi. Just reporting a few inconsistencies following the upgrade.
1. Instructions at https://www.matthewthom.as/mirrors/#zoom haven't been updated.
2. Previously your GPG key was saved to /usr/share/keyrings/mwt.asc . If this is the case then it's not sufficient to just rerun Step 2 as stated in the README as this requires the GPG key to be /etc/apt/keyrings/mwt.asc .

**Comment by mwt** [comment]
Yes. The key was moved to `/etc/apt/keyrings/mwt.asc` a little over a year ago.

I'll just change it to tell people to rerun both steps.
