### ISSUE TITLE
A new version of zoom has been released

### ISSUE THREAD

**Issue by gamer191** [mwt/zoom-apt-repo#3]
There's a new version of zoom out (`5.12.6 (173)`)

PS: thanks heaps for this repo, it's very useful

**Comment by mwt** [comment]
It seems that they signed this version with a different gpg key without announcing any key change on their site?!? I could force an update, but I think it's better to be paranoid for now.

**Comment by gamer191** [comment]
@mwt It's buried deep in their site, but I think [this](https://support.zoom.us/hc/en-us/articles/9836712961165-Downloading-the-public-key-for-Linux) is meant to be the key change announcement:
>In November 2022, Zoom is retiring the current key pair used to sign the Zoom desktop client for Linux, which customers can use to validate the Zoom desktop client. Users must download the new public key before attempting to upgrade to version 5.12.6, otherwise they will be unable to install this update. Prior versions (before 5.12.6) will not be impacted.

> For versions 5.12.6 and higher, the Linux and Docker GPG signature thumbprint will change from "Key fingerprint: 3960 60CA DD8A 7522 0BFC B369 B903 BF18 61A7 C71D" to "Key fingerprint: 59C8 6188 E22A BB19 BD55 4047 7B04 A1B8 DD79 B481".

DISCLAIMER: I know nothing about GPG keys, I hadn't even heard of them before today!

PS: I completely agree that it's better to be paranoid then risking distributing malware

**Comment by mwt** [comment]
Thanks! I loaded the new gpg key and zoom should be updated in the repo soon.

**Comment by gamer191** [comment]
> zoom should be updated in the repo soon

Yep, I just updated!

Thanks for the fast response, and have an awesome day!
