### ISSUE TITLE
Mirror for rpms

### ISSUE THREAD

**Issue by ghost** [mwt/zoom-apt-repo#4]
Would it be possible to extend this concept to yum repos, so that fedora/opensuse can also update zoom/rstudio through a repository?

**Comment by mwt** [comment]
Yes. It should be pretty simple. I did this for rclone a while back.

When I made this, I didn't know how to make RPM repositories. I think I should rewrite this based on the rclone base and support both deb and rpm at some point in the future.

**Comment by mwt** [comment]
This is now complete over here: https://github.com/mirror-mwt/makerepo-docker

I'll make the repo public on the internet once I figure out the transition.
