### ISSUE TITLE
Cannot resolve mirror.mwt.me

### ISSUE THREAD

**Issue by SwooshyCueb** [mwt/zoom-apt-repo#7]
apt-get and pkcon both complain about being unable to resolve mirror.mwt.me. Seems like maybe the domain expired?

**Comment by mwt** [comment]
Could you try going to:

https://mirror.mwt.me/my/

And tell me what you see? Domain is up and all four nodes are operational. Maybe it's an unfortunate security block?

**Comment by SwooshyCueb** [comment]
In Chrome, I get DNS_PROBE_FINISHED_NXDOMAIN error

**Comment by SwooshyCueb** [comment]
`dig` reports the domain has no `A` records:
```
; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> mirror.mwt.me
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 52953
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;mirror.mwt.me.                 IN      A

;; Query time: 52 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Jul 03 10:33:50 EDT 2023
;; MSG SIZE  rcvd: 42
```

**Comment by SwooshyCueb** [comment]
Upon further investigation, it appears this is a problem with the DNS servers at my office, specifically. Resolution works fine with Google DNS, Cloudflare DNS, and UNC-CH DNS.

Apologies for taking your time.

**Comment by mwt** [comment]
No problem! I'm still interested in hearing that people are blocking my domain!
