### ISSUE TITLE
Seems to have stopped updating Zoom

### ISSUE THREAD

**Issue by someperson** [mwt/zoom-apt-repo#8]
https://mirror.mwt.me/my/deb/ doesn't have any versions newer than 5.17.11.

See https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0068973

**Comment by dairiki** [comment]
FWIW, the repo seems to have been updated (~ two days ago) to 6.0.2.4680.  (That is the latest stable release from Zoom.)

**Comment by mwt** [comment]
Thanks @someperson and @dairiki! It was a hardware mounting issue. All of my mirrors were stale by almost a month 😅.

**Comment by dairiki** [comment]
Thank you, @mwt!
